### ISSUE TITLE
System avrdude is not found

### ISSUE THREAD

**Issue by Aentfs** [arduino-cmake/Arduino-CMake-NG#62]
As the `avrdude` should not be part of the sdk path and is therefore not installed there by the package manager (as the `avrdude` is usable without the sdk) it needs to be found on its own. The dependencies of this project even list `avrdude` as a separate package to be installed.

This is related to issue: #53

P.S. I'm on arch linux

**Comment by MrPointer** [comment]
@Aentfs Well, as commented in #53, it's indeed not supported yet, so there's no point of re-discussing it until then.
With that being said, you could try and introduce support for this by yourself and PR it when it's ready 😃
