### ISSUE TITLE
vidor 4000

### ISSUE THREAD

**Issue by Sausy** [arduino-cmake/Arduino-CMake-NG#86]
I was wondering if the vidor 4000 is currently supported?

**Comment by MrPointer** [comment]
@Sausy Hi, I'm afraid not - The framework currently doesn't support anything beyond the "casual" Arduino.
However, that depends on whether the **vidor** is considered a standard board, i.e. part of the basic SDK
If it is, it's probably supported and you should definitely give it a try!
